"""Recover integer labels from a napari-saved SVG (which embeds a rendered PNG).

napari-svg saves Labels as RGBA PNG with the layer's colormap applied. We
extract the PNG, find unique RGBA colors, and map each to its label integer
by reproducing napari's labels colormap.
"""
from __future__ import annotations
import argparse, base64, re
from pathlib import Path
import numpy as np
import tifffile
from PIL import Image
import io

# napari uses a procedural shuffled colormap for Labels. We reproduce it:
# https://github.com/napari/napari/blob/main/napari/utils/colormaps/_color_data.py
# The default cycle is generated by `low_discrepancy_image` which we can call.

def get_napari_label_colors(n_max: int = 50):
    """Reproduce napari's default Labels colormap. Returns dict {label_int: (R,G,B,A) uint8}."""
    try:
        from napari.utils.colormaps import label_colormap
        cmap = label_colormap(n_max)
        out = {}
        for lbl in range(n_max + 1):
            rgba = cmap.map(np.array([lbl]))[0]
            out[lbl] = tuple((rgba * 255).astype(int))
        return out
    except Exception as e:
        print(f"napari colormap fallback ({e})")
        # fallback: get from a live napari Labels layer briefly
        import napari
        v = napari.Viewer(show=False)
        L = v.add_labels(np.arange(n_max + 1, dtype=np.int32).reshape(1, -1))
        out = {}
        for lbl in range(n_max + 1):
            rgba = L._data_to_color(np.array([lbl]))[0]
            out[lbl] = tuple((rgba * 255).astype(int))
        v.close()
        return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("svg", type=Path)
    ap.add_argument("--out", type=Path, default=None,
                    help="output TIFF path (default: same dir, _corrected.tif)")
    ap.add_argument("--max_label", type=int, default=10)
    args = ap.parse_args()

    svg_text = args.svg.read_text()
    # find xlink:href="data:image/png;base64,..."
    match = re.search(r'data:image/png;base64,([^"]+)', svg_text)
    if not match:
        print("no embedded PNG found in SVG"); return
    png_bytes = base64.b64decode(match.group(1))
    img = Image.open(io.BytesIO(png_bytes))
    rgba = np.asarray(img.convert("RGBA"))
    H, W = rgba.shape[:2]
    print(f"recovered RGBA image: ({H},{W},{rgba.shape[2]})  dtype={rgba.dtype}")

    # transparent pixels = label 0 (background)
    alpha = rgba[..., 3]
    bg_mask = alpha == 0

    # build expected color → label map (alpha set to napari's default opacity 0.7)
    color_map = get_napari_label_colors(args.max_label)
    print("napari colormap (label -> RGBA):")
    for lbl, c in color_map.items():
        print(f"  {lbl}: {c}")

    # For each unique non-background color in the image, find the closest label
    # color (use only RGB, ignore alpha because the layer's opacity scales it).
    flat = rgba[~bg_mask][:, :3]    # (N, 3)
    if len(flat) == 0:
        print("no foreground pixels"); return
    # quantise to nearest 8 to merge near-duplicates
    qflat = (flat // 8) * 8
    uniq, inv, counts = np.unique(qflat, axis=0, return_inverse=True, return_counts=True)
    print(f"\nfound {len(uniq)} unique foreground colors:")
    for i in range(len(uniq)):
        if counts[i] < 1000: continue   # skip tiny noise
        print(f"  rgb={tuple(int(v) for v in uniq[i])}  n={counts[i]}")

    # match to napari labels (RGB-only, label color * opacity may not match raw RGB
    # because napari blends with image; instead match on relative dominance per channel)
    # Simpler: try matching to label colors directly, assuming user kept opacity=0.45
    # which we set in the launcher. The label color lookup gives RGB at full opacity;
    # the saved RGBA has alpha = 0.45 but RGB is unchanged in napari-svg's render.
    label_rgb = {lbl: np.array(c[:3]) for lbl, c in color_map.items() if lbl > 0}
    out = np.zeros((H, W), dtype=np.uint8)
    for i in range(len(uniq)):
        if counts[i] < 100: continue
        col = uniq[i].astype(int)
        dists = {lbl: np.linalg.norm(col - lc) for lbl, lc in label_rgb.items()}
        best_lbl, best_d = min(dists.items(), key=lambda x: x[1])
        if best_d > 60:
            print(f"  WARN: rgb={tuple(int(v) for v in col)} no good match "
                  f"(best={best_lbl} dist={best_d:.0f})")
            continue
        # set all pixels with this quantised color to best_lbl
        match_mask = np.all(np.abs(rgba[..., :3].astype(int) - col) < 8, axis=-1) & ~bg_mask
        out[match_mask] = best_lbl

    # report
    uvals, ucounts = np.unique(out, return_counts=True)
    print(f"\nfinal label distribution:")
    for u, c in zip(uvals, ucounts):
        print(f"  label {u}: {c} px")

    out_path = args.out or (args.svg.parent / args.svg.stem.replace("_labeld", "_corrected") + ".tif")
    if isinstance(out_path, str): out_path = Path(out_path)
    tifffile.imwrite(out_path, out, compression="zlib")
    print(f"\nsaved {out_path}")


if __name__ == "__main__":
    main()
